---
# Copyright 2026 markurtz
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
pyproject_changes:
  - 'pyproject.toml'
  - 'uv.lock'
github_changes:
  - '.github/**'
docs_changes:
  - 'docs/**'
  - 'examples/**/*.md'
  - "*.md"
  - "zensical.toml"
examples_changes:
  - "examples/**"
scripts_changes:
  - "scripts/**/*.py"
src_changes:
  - "src/**/*.py"
tests_changes:
  - "tests/**/*.py"
oci_changes:
  - '.devcontainer/**'
  - "Dockerfile"
  - "docker-compose.yml"
  - "cst.yaml"
project_changes:
  - "**/*.md"
  - "**/*.toml"
  - "**/*.txt"
  - "**/*.yaml"
  - "**/*.yml"
  - ".gitignore"
  - ".yamllint"
