---
name: gitversioned
services:
  app:
    build:
      context: .
      target: builder
    volumes:
      - ./src:/app/src
    environment:
      - APP_ENV=${APP_ENV:-development}
      - APP_DEBUG=${APP_DEBUG:-true}
    ports:
      - '127.0.0.1:${APP_PORT:-8080}:8080'
    # Standard Python development command
    command:
      - "python"
      - "-m"
      - "gitversioned"
