# Copyright 2026 markurtz
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[project]
site_name = "gitversioned"
site_url = "https://markurtz.github.io/git-versioned/"
site_description = "Opinionated PEP 440 Python versioning for Git repos and submodules. Enforces CI/User authority and generates rich version.py files with deep metadata for auditability. Native Hatch & Setuptools support. Simple, predictable, and foolproof automation."
site_author = "markurtz"
repo_url = "https://github.com/markurtz/git-versioned"
repo_name = "markurtz/git-versioned"

[project.extra.version]
provider = "mike"
default = "latest"


[project.theme]
variant = "modern"
features = ["navigation.indexes"]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.plugins.macros]
module_name = "docs/scripts/macros"

[project.plugins.mkdocstrings]
handlers = { python = { paths = ["src"] } }
