---
# Copyright 2026 markurtz
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: "Set Up Git"
description: "Standardized setup and configuration for Git credentials and environment in\
  \ CI"
inputs:
  user-name:
    description: "Git user name"
    required: false
    default: "github-actions[bot]"
  user-email:
    description: "Git user email"
    required: false
    default: "github-actions[bot]@users.noreply.github.com"
runs:
  using: "composite"
  steps:
    - name: Configure Git Credentials and Environment
      shell: bash
      env:
        USER_NAME: ${{ inputs.user-name }}
        USER_EMAIL: ${{ inputs.user-email }}
      run: |-
        echo "[INFO] Configuring standardized Git user and environment..."
        git config --global user.name "$USER_NAME"
        git config --global user.email "$USER_EMAIL"
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
